# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: trigger tests in another repository
on: workflow_dispatch
jobs:
  trigger-test:
    runs-on: ubuntu-latest
    steps:
      - name: trigger the automated test in another repo
        uses: kiran-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: kondekiran/nestt
          event-type: my-event
          client-payload: '{"github": ${{ toJson(github) }}}'
      
     
